services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "


    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    depends_on:
      - db

volumes:
  mysql_data:
  bundle_data:
